### ISSUE TITLE
Couldn't find adapter to handle this event with serverless-offline

### ISSUE THREAD

**Issue by Capo93** [H4ad/serverless-adapter#310]
## Current Behavior

I follow this example: https://github.com/H4ad/serverless-adapter-examples/tree/master/examples/fastify-aws-stream and try to setup my Lambda lith application with serverless-adapter, fastify and [serverless](https://www.serverless.com/).

my idea is to use serverless for deployment and serverless-offline for development. 

When I run the application locally I get this error:
```
✖ Unhandled exception in handler 'entrypoint'.
✖ Error: SERVERLESS_ADAPTER: Couldn't find adapter to handle this event.
      at x.getAdapterByEventAndContext (/packages/api/node_modules/@h4ad/serverless-adapter/src/core/base-handler.ts:77:13)
      at <anonymous> (/packages/api/node_modules/@h4ad/serverless-adapter/src/handlers/default/default.handler.ts:66:28)
      at InProcessRunner.run (file:////node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/InProcessRunner.js:87:20)
      at async MessagePort.<anonymous> (file:////node_modules/serverless-offline/src/lambda/handler-runner/worker-thread-runner/workerThreadHelper.js:24:14)
✖ SERVERLESS_ADAPTER: Couldn't find adapter to handle this event.
``` 

## Steps to Reproduce the Problem

my code:

`serverless-adapter.ts`:
```
import { createDefaultLogger, ServerlessAdapter } from '@h4ad/serverless-adapter';
import { ApiGatewayV2Adapter, SQSAdapter } from '@h4ad/serverless-adapter/lib/adapters/aws';
import { FastifyFramework } from '@h4ad/serverless-adapter/lib/frameworks/fastify';
import { DefaultHandler } from '@h4ad/serverless-adapter/lib/handlers/default';
import { PromiseResolver } from '@h4ad/serverless-adapter/lib/resolvers/promise';

import { app } from './fastify-app';

export const handler = ServerlessAdapter.new(app)
  .setFramework(new FastifyFramework())
  .setHandler(new DefaultHandler())
  .setResolver(new PromiseResolver())
  // disable debug mode to not produce too much logs
  .setLogger(createDefaultLogger({ level: 'debug' }))
  .addAdapter(new ApiGatewayV2Adapter())
  .addAdapter(new SQSAdapter(/*{ sqsForwardPath: '/local'}*/))
  .build();
```

`fastify-app.ts`:

```
import fastify from 'fastify';

import sqsRoutes from '../routes/sqs';
import rolesRoutes from '../routes/roles';

let app = fastify();

const routes = [
  rolesRoutes,
  sqsRoutes,
]

for (const route of routes){
  app?.register(route);
};

export { app };
```

`roles-routes.ts`:

```
import {
  RequestBodyDefault,
  RequestParamsDefault,
  FastifyInstance,
  RouteShorthandOptions,
  RequestQuerystringDefault,
  RequestHeadersDefault,
} from 'fastify';

import * as RolesController from '../controllers/roles-controller';

async function routes(fastify: FastifyInstance) {
  fastify.get<{
    Body: RequestBodyDefault;
    Querystring: RequestQuerystringDefault;
    Params: RequestParamsDefault;
    Headers: RequestHeadersDefault;
    // Reply: RouteServiceGetSerial;
  }>(
    '/roles',
    async (req, reply) => {      
      const roles = RolesController.getAll();
      return reply.send(roles);
    }
  );

  fastify.post(
    '/roles',
    async (req, reply) => {
     return 'TODO'
    }
  );
}

export default routes;
```

`serverless.yaml`:

```
service: name
useDotenv: true

plugins:
  - serverless-offline
  - serverless-domain-manager

package:
  individually: true

custom:
  dotenv:
    basePath: ./
    logging: true
  customDomain:
    domainName: ${env:DOMAIN}
    stage: ${env:STAGE}
    basePath: api
    createRoute53Record: true
    autoDomain: false

provider:
  name: aws
  runtime: nodejs22.x
  deploymentMethod: direct
  region: ${env:REGION}
  versionFunctions: ${env:VERSION_FUNCTIONS}
  logRetentionInDays: 5
  tracing:
    apiGateway: true
    lambda: true
  profile: ${env:PROFILE}
  timeout: 30

functions:
  entrypoint:
    handler: src/handlers/serverless-adapter.handler
    events:
      - http:
          path: /{path+}
          method: "*"
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
```

Command:

```
sls offline
```

LOG:

```
Starting Offline at stage dev (eu-west-1)

Offline [http for lambda] listening on http://localhost:3002
Function names exposed for local invocation by aws-sdk:
   * entrypoint: entrypoint

   ┌──────────────────────────────────────────────────────────────────────────────┐
   │                                                                              │
   │   *    | http://localhost:3000/dev/{path*}                                   │
   │   POST | http://localhost:3000/2015-03-31/functions/entrypoint/invocations   │
   │                                                                              │
   └──────────────────────────────────────────────────────────────────────────────┘

Server ready: http://localhost:3000 🚀
```

then when i call GET http://localhost:3000/dev/roles (witch is a registered route) i got the error described. 

## Environment

- Version: 4.4.0
- Platform: Mac
- Node.js Version: 22.12.0
